"""Experimental canonical binary partitions for rectangular grids.

This package provides NumPy/SciPy reference implementations for one
deterministic binary tree, immutable active frontiers, Gaussian projection and
partition objectives, local proposals, and stochastic local search. It is
provisional and is not re-exported from :mod:`openghg_inversions.basis`.
"""

from .contrast import TreeContrastLayout
from .calibration import (
    AggregatePriorMoments,
    RootVarianceCalibration,
    aggregate_prior_moments,
    calibrate_group_root_variance,
)
from .covariance_fit import (
    ExponentialLengthScaleFit,
    fit_projected_exponential_length_scale,
    fit_separable_exponential_length_scale,
    grouped_exponential_covariance,
    projected_exponential_covariance,
    separable_exponential_correlation,
)
from .demo_runner import (
    DemoSearchConfig,
    DemoSearchRun,
    ProjectedVariableKSearchRun,
    VariableKSearchConfig,
    VariableKSearchRun,
    excess_region_penalty,
    run_fixed_count_dfs_search,
    run_projected_variable_k_dfs_search,
    run_variable_k_dfs_search,
)
from .dynamic_programming import (
    AdditivePartitionSolution,
    additive_partition_frontier,
    optimal_additive_partition,
)
from .enumeration import enumerate_partitions
from .gaussian_product_space import (
    GaussianConditional,
    GaussianProductSpaceTarget,
    PartitionLogPrior,
)
from .gamma_beta import (
    DepthKappaStrategy,
    GammaBetaChildMoments,
    GammaBetaForest,
    GammaBetaGroupSpec,
    GammaBetaNode,
    GammaBetaSamples,
    GammaBetaSplitContext,
    KappaStrategy,
    MomentSplitConstraint,
    gamma_beta_child_moments,
)
from .gaussian_projection import (
    BocquetProjection,
    GaussianPosterior,
    GaussianProjectionAnalysis,
    build_bocquet_projection,
    equation_45_objective,
    gaussian_projection_oracle,
    native_gaussian_posterior,
    projected_bayesian_information_gain,
    projected_bayesian_kl,
    projected_dfs,
    projected_fisher_aggregation_aware,
    projected_fisher_base_r,
    reduced_gaussian_posterior,
    restriction_for_prolongation,
)
from .grid_covariance import SeparableGridCovariance
from .initializers import InitializationResult, greedy_partition, random_partition, threshold_partition
from .multiscale import CoarsenedGrid, MultiscaleDesign, direct_gather, sum_coarsen_grid
from .objectives import (
    CovarianceBuilder,
    GaussianDFSObjective,
    IsotropicRegionCovariance,
    direct_observation_space_dfs,
    gaussian_dfs,
    isotropic_observation_space_dfs,
    prototype_quadratic_tile_scores,
)
from .partition_diagnostics import (
    GaussianPartitionDiagnostics,
    GaussianPartitionObjectives,
    build_partition_diagnostics,
    emissions_compression_quality,
    gaussian_partition_objectives,
    gaussian_posterior_mean,
)
from .proposals import (
    MergeMove,
    Move,
    PairedMove,
    PairedNeighbor,
    SplitMove,
    apply_move,
    enumerate_merge_moves,
    enumerate_paired_moves,
    enumerate_paired_neighbors,
    enumerate_split_moves,
    reverse_move,
)
from .product_space import (
    LogAugmentedDensity,
    PartitionMove,
    PartitionNeighbor,
    ProductSpaceState,
    ProductSpaceTransition,
    enumerate_partition_neighbors,
    partition_metropolis_step,
)
from .rhime_gaussian import NativePosteriorMarginals, RHIMEGaussianMultiscale
from .search import (
    PiecewiseGeometricSchedule,
    SearchProposal,
    SearchResult,
    SearchStep,
    TemperatureSchedule,
    stochastic_local_search,
)
from .state import PartitionState
from .tree import DyadicTree, NodeId, Tile

__all__ = [
    "AdditivePartitionSolution",
    "AggregatePriorMoments",
    "BocquetProjection",
    "CoarsenedGrid",
    "CovarianceBuilder",
    "DemoSearchConfig",
    "DemoSearchRun",
    "DepthKappaStrategy",
    "DyadicTree",
    "ExponentialLengthScaleFit",
    "GammaBetaChildMoments",
    "GammaBetaForest",
    "GammaBetaGroupSpec",
    "GammaBetaNode",
    "GammaBetaSamples",
    "GammaBetaSplitContext",
    "GaussianDFSObjective",
    "GaussianConditional",
    "GaussianPartitionDiagnostics",
    "GaussianPartitionObjectives",
    "GaussianPosterior",
    "GaussianProjectionAnalysis",
    "GaussianProductSpaceTarget",
    "InitializationResult",
    "IsotropicRegionCovariance",
    "KappaStrategy",
    "LogAugmentedDensity",
    "MergeMove",
    "Move",
    "MomentSplitConstraint",
    "MultiscaleDesign",
    "NativePosteriorMarginals",
    "NodeId",
    "PairedMove",
    "PairedNeighbor",
    "PartitionLogPrior",
    "PartitionMove",
    "PartitionNeighbor",
    "PartitionState",
    "PiecewiseGeometricSchedule",
    "ProjectedVariableKSearchRun",
    "ProductSpaceState",
    "ProductSpaceTransition",
    "RHIMEGaussianMultiscale",
    "RootVarianceCalibration",
    "SearchProposal",
    "SearchResult",
    "SearchStep",
    "SeparableGridCovariance",
    "SplitMove",
    "TemperatureSchedule",
    "Tile",
    "TreeContrastLayout",
    "VariableKSearchConfig",
    "VariableKSearchRun",
    "apply_move",
    "aggregate_prior_moments",
    "additive_partition_frontier",
    "build_partition_diagnostics",
    "build_bocquet_projection",
    "calibrate_group_root_variance",
    "direct_gather",
    "direct_observation_space_dfs",
    "enumerate_merge_moves",
    "enumerate_partition_neighbors",
    "enumerate_partitions",
    "enumerate_paired_moves",
    "enumerate_paired_neighbors",
    "enumerate_split_moves",
    "emissions_compression_quality",
    "equation_45_objective",
    "excess_region_penalty",
    "fit_separable_exponential_length_scale",
    "fit_projected_exponential_length_scale",
    "gaussian_dfs",
    "gamma_beta_child_moments",
    "gaussian_partition_objectives",
    "gaussian_projection_oracle",
    "gaussian_posterior_mean",
    "isotropic_observation_space_dfs",
    "native_gaussian_posterior",
    "greedy_partition",
    "grouped_exponential_covariance",
    "optimal_additive_partition",
    "partition_metropolis_step",
    "prototype_quadratic_tile_scores",
    "projected_bayesian_information_gain",
    "projected_bayesian_kl",
    "projected_dfs",
    "projected_fisher_aggregation_aware",
    "projected_fisher_base_r",
    "projected_exponential_covariance",
    "random_partition",
    "reduced_gaussian_posterior",
    "restriction_for_prolongation",
    "reverse_move",
    "run_fixed_count_dfs_search",
    "run_projected_variable_k_dfs_search",
    "run_variable_k_dfs_search",
    "separable_exponential_correlation",
    "stochastic_local_search",
    "sum_coarsen_grid",
    "threshold_partition",
]
