[forward]
type = "forward model"

[forward.flux]
type = "flux"

[forward.baseline]
type = "baseline"
optional = true

[forward.baseline.bc]
type = "bc"
optional = true

[forward.baseline.offset]
type = "offset"
optional = true

[likelihood]
type = "rhime likelihood"
inputs = ["forward"]
