"""Compatibility imports; implementation lives in :mod:`openghg_inversions.recipes.nested`."""

from openghg_inversions.recipes.nested import (
    NestedRhimePreparedInputs as NestedRhimePreparedInputs,
    NestedRhimeResult as NestedRhimeResult,
    _NESTED_PARAMETER_NAMES as _NESTED_PARAMETER_NAMES,
    _PREPARED_OVERLAP_MASK_POLICY as _PREPARED_OVERLAP_MASK_POLICY,
    _RETRIEVAL_OVERLAP_MASK_POLICY as _RETRIEVAL_OVERLAP_MASK_POLICY,
    _allocate_nested_nbasis as _allocate_nested_nbasis,
    _domain_variable_roles as _domain_variable_roles,
    _grid_identity as _grid_identity,
    _inner_domain_name as _inner_domain_name,
    _inner_measurement_positions as _inner_measurement_positions,
    _mask_spatial_variables as _mask_spatial_variables,
    _measurement_index as _measurement_index,
    _nested_domain_artifact_metadata as _nested_domain_artifact_metadata,
    _nested_sensitivity_reductions as _nested_sensitivity_reductions,
    _prepare_one_domain as _prepare_one_domain,
    _replace_data_object_data as _replace_data_object_data,
    _retain_common_sites as _retain_common_sites,
    _select_merged_sites as _select_merged_sites,
    _state_dimension as _state_dimension,
    _validate_one_to_one_inner_time_matches as _validate_one_to_one_inner_time_matches,
    _write_nested_paris_outputs as _write_nested_paris_outputs,
    align_inner_merged_to_outer_observations as align_inner_merged_to_outer_observations,
    build_nested_rhime_model as build_nested_rhime_model,
    build_nested_rhime_model_result as build_nested_rhime_model_result,
    combine_nested_rhime_inputs as combine_nested_rhime_inputs,
    make_nested_inversion_outputs as make_nested_inversion_outputs,
    mask_outer_merged_for_inner_domain as mask_outer_merged_for_inner_domain,
    nested_model_input_names as nested_model_input_names,
    prepare_nested_rhime_inputs as prepare_nested_rhime_inputs,
    run_rhime_nested as run_rhime_nested,
    run_rhime_nested_from_prepared_inputs as run_rhime_nested_from_prepared_inputs,
)

__all__ = ['NestedRhimePreparedInputs', 'NestedRhimeResult', 'build_nested_rhime_model', 'build_nested_rhime_model_result', 'align_inner_merged_to_outer_observations', 'combine_nested_rhime_inputs', 'make_nested_inversion_outputs', 'mask_outer_merged_for_inner_domain', 'nested_model_input_names', 'prepare_nested_rhime_inputs', 'run_rhime_nested', 'run_rhime_nested_from_prepared_inputs']
