"""RHIME output construction and persistence helpers."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, cast

import arviz as az
import numpy as np
import xarray as xr

from openghg_inversions._timing import timed
from openghg_inversions.inversion_data import RhimePreparedInputs
from openghg_inversions.models import RhimeModelSpec
from openghg_inversions.postprocessing.inversion_output import InversionOutput
from openghg_inversions.rhime.sampling import RhimeSampler
from openghg_inversions.rhime.specs import OutputFilenameConvention, RhimeOutputSpec, RhimeRunSpec
from openghg_inversions.serialization import reset_serialisation_multiindexes
from openghg_inversions.utils import ncdf_encoding, write_netcdf_preserving_bounds_attrs


@dataclass(frozen=True)
class RhimeOutputBundle:
    """Outputs and metadata generated by RHIME output helpers."""

    inv_out: InversionOutput | None = None
    outputs: dict[str, Any] = field(default_factory=dict)
    output_metadata: dict[str, Any] = field(default_factory=dict)


def _structured_metadata(value: Any) -> Any:
    """Convert array-backed spec values to lossless JSON-compatible metadata.

    Args:
        value: Nested metadata value, possibly backed by NumPy or xarray.

    Returns:
        Scalars and recursively structured dictionaries/lists. DataArrays keep
        explicit dimensions, dimension coordinates, and values.
    """
    if isinstance(value, xr.DataArray):
        materialized = value.compute()
        return {
            "dims": [str(dim) for dim in materialized.dims],
            "coords": {
                str(dim): _structured_metadata(materialized.coords[dim].to_numpy())
                for dim in materialized.dims
                if dim in materialized.coords
            },
            "values": _structured_metadata(materialized.to_numpy()),
        }
    if isinstance(value, np.ndarray):
        if value.ndim == 0:
            return _structured_metadata(value.item())
        return [_structured_metadata(item) for item in value.tolist()]
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, dict):
        return {str(key): _structured_metadata(item) for key, item in value.items()}
    if isinstance(value, tuple | list):
        return [_structured_metadata(item) for item in value]
    return value


def _resolve_output_path(
    save_setting: str | Path | bool, output_path: str | None, filename: str
) -> Path | None:
    """Resolve an optional output path from a bool/path save setting."""
    if not save_setting:
        return None
    if isinstance(save_setting, str | Path):
        return Path(save_setting)
    if output_path is None:
        raise ValueError("An output path is required when saving RHIME artifacts.")
    return Path(output_path) / filename


def _define_output_filename(
    output_path: str | Path,
    species: str,
    domain: str,
    output_name: str,
    start_date: str,
    *,
    filename_convention: OutputFilenameConvention = "rhime",
    ext: str = ".nc",
) -> Path:
    """Create a derived NetCDF filename using the selected convention."""
    if filename_convention == "legacy":
        filename = f"{species.upper()}_{domain}_{output_name}_{start_date}{ext}"
    else:
        filename = f"{output_name}_{species}_{domain}_{start_date}{ext}"
    return Path(output_path) / filename


def _define_derived_output_filename(
    output_spec: RhimeOutputSpec,
    *,
    species: str,
    domain: str,
    output_name: str,
    start_date: str,
    ext: str = ".nc",
) -> Path:
    """Create a derived-output filename using the requested convention."""
    if output_spec.output_path is None:
        raise ValueError("An output path is required when saving RHIME outputs.")
    return _define_output_filename(
        output_spec.output_path,
        species,
        domain,
        output_name,
        start_date,
        filename_convention=output_spec.output_filename_convention,
        ext=ext,
    )


def _save_inferencedata(idata: az.InferenceData, path: str | Path) -> None:
    """Save inference data while preserving metadata and serializable coords.

    Root and group attributes are preserved while group MultiIndexes are reset
    on a serialization copy. The h5netcdf, ArviZ-default, and netcdf4 backends
    are attempted in that order.

    Args:
        idata: Inference data to serialize.
        path: Destination NetCDF path.

    Raises:
        RuntimeError: If every supported NetCDF backend fails.
    """
    if isinstance(idata, az.InferenceData):
        idata = cast(Any, az.InferenceData)(
            attrs=dict(idata.attrs),
            **{group: reset_serialisation_multiindexes(idata[group]) for group in idata.groups()},
        )

    failures = []
    for engine in ("h5netcdf", None, "netcdf4"):
        try:
            if engine is None:
                idata.to_netcdf(str(path), compress=True)
            else:
                idata.to_netcdf(str(path), engine=engine, compress=True)
        except Exception as exc:
            engine_name = "arviz-default" if engine is None else engine
            failures.append(f"{engine_name}: {exc}")
        else:
            return

    joined_failures = "\n".join(failures)
    raise RuntimeError(
        f"Could not save RHIME trace to {path}. Tried h5netcdf, ArviZ default, and netcdf4:\n{joined_failures}"
    )


def _make_inversion_output(
    *,
    prepared: RhimePreparedInputs,
    idata: az.InferenceData,
    run_spec: RhimeRunSpec,
    model_spec: RhimeModelSpec,
    output_spec: RhimeOutputSpec,
    sampler: RhimeSampler | None = None,
) -> InversionOutput:
    """Create the modern RHIME InversionOutput without fixedbasis legacy adapters."""
    return InversionOutput(
        inv_inputs=prepared.inv_inputs,
        basis_functions=prepared.basis_functions,
        trace=idata,
        run_metadata={
            "start_date": run_spec.start_date,
            "end_date": run_spec.end_date,
            "sites": list(run_spec.sites),
            "averaging_period": list(run_spec.averaging_period),
            "split_by_sectors": run_spec.split_by_sectors,
            "basis_artifact_source": prepared.basis_artifact_source,
            "basis_artifact_path": prepared.basis_artifact_path,
        },
        model_metadata=cast(dict[str, Any], _structured_metadata(asdict(model_spec))),
        output_metadata={
            "output_format": output_spec.output_format,
            "output_path": output_spec.output_path,
            "output_name": output_spec.output_name,
            "save_trace": output_spec.save_trace,
            "save_inversion_output": output_spec.save_inversion_output,
            "sampler": _sampler_metadata(sampler),
        },
        provenance={
            "contract": "modern_rhime_inversion_output",
            "compatibility_issue": "401",
            "basis_representation": "operator-backed",
        },
    )


def _sampler_metadata(sampler: RhimeSampler | None) -> dict[str, int | str] | None:
    """Return serialisable sampler metadata for compatibility output attrs."""
    if sampler is None:
        return None
    return {
        "draws": sampler.draws,
        "burn": sampler.burn,
        "tune": sampler.tune,
        "chains": sampler.chains,
        "nuts_sampler": sampler.nuts_sampler,
    }


def make_standard_output_bundle(
    *,
    output_spec: RhimeOutputSpec,
    run_spec: RhimeRunSpec,
    model_spec: RhimeModelSpec,
    idata: az.InferenceData,
    prepared: RhimePreparedInputs,
    country_file: str | None,
    sampler: RhimeSampler | None = None,
) -> RhimeOutputBundle:
    """Create and optionally save standard RHIME outputs."""
    if output_spec.output_format == "none":
        return RhimeOutputBundle()

    outputs: dict[str, Any] = {}
    output_metadata: dict[str, Any] = {}
    with timed("rhime.output.inversion_output_create", output_format=output_spec.output_format):
        inv_out = _make_inversion_output(
            prepared=prepared,
            idata=idata,
            run_spec=run_spec,
            model_spec=model_spec,
            output_spec=output_spec,
            sampler=sampler,
        )
    outputs["inversion_output"] = inv_out
    output_metadata["inversion_output_contract"] = "modern"

    trace_path = _resolve_output_path(
        output_spec.save_trace,
        output_spec.output_path,
        f"{output_spec.output_name}{run_spec.start_date}_trace.nc",
    )
    if trace_path is not None:
        trace_path.parent.mkdir(parents=True, exist_ok=True)
        with timed("rhime.output.trace_save", path=trace_path):
            _save_inferencedata(idata, trace_path)
        output_metadata["trace_path"] = str(trace_path)

    inv_out_path = _resolve_output_path(
        output_spec.save_inversion_output,
        output_spec.output_path,
        f"{output_spec.output_name}{run_spec.start_date}_inversion_output.nc",
    )
    if inv_out_path is not None:
        inv_out_path.parent.mkdir(parents=True, exist_ok=True)
        with timed("rhime.output.inversion_output_save", path=inv_out_path):
            inv_out.save(inv_out_path)
        output_metadata["inversion_output_path"] = str(inv_out_path)

    if output_spec.output_format == "basic":
        from openghg_inversions.postprocessing.make_outputs import basic_output

        output_metadata["postprocessing_input_contract"] = "modern_inversion_output"
        with timed("rhime.output.basic_postprocess"):
            outputs["basic"] = basic_output(inv_out, country_file=country_file)
    elif output_spec.output_format == "paris":
        from openghg_inversions.postprocessing.make_paris_outputs import make_paris_outputs

        output_metadata["postprocessing_input_contract"] = "modern_inversion_output"
        obs_avg_period = prepared.averaging_period[0] or "0h"
        kwargs = output_spec.paris_postprocessing_kwargs or {}
        with timed("rhime.output.paris_postprocess"):
            flux_outs, conc_outs = make_paris_outputs(
                inv_out,
                country_file=country_file,
                domain=model_spec.domain,
                obs_avg_period=obs_avg_period,
                **kwargs,
            )
        outputs["paris_flux"] = flux_outs
        outputs["paris_concentration"] = conc_outs

        if output_spec.output_path is not None:
            Path(output_spec.output_path).mkdir(parents=True, exist_ok=True)
            conc_file = _define_derived_output_filename(
                output_spec,
                species=model_spec.species,
                domain=model_spec.domain,
                output_name=output_spec.output_name + "_conc",
                start_date=run_spec.start_date,
                ext=".nc",
            )
            flux_file = _define_derived_output_filename(
                output_spec,
                species=model_spec.species,
                domain=model_spec.domain,
                output_name=output_spec.output_name + "_flux",
                start_date=run_spec.start_date,
                ext=".nc",
            )
            with timed("rhime.output.paris_concentration_netcdf_write", path=conc_file):
                write_netcdf_preserving_bounds_attrs(conc_outs, conc_file, unlimited_dims=["time"])
            with timed("rhime.output.paris_flux_netcdf_write", path=flux_file):
                write_netcdf_preserving_bounds_attrs(flux_outs, flux_file, unlimited_dims=["time"])
            output_metadata["paris_concentration_path"] = str(conc_file)
            output_metadata["paris_flux_path"] = str(flux_file)
    elif output_spec.output_format == "legacy":
        from openghg_inversions.postprocessing.legacy_outputs import make_legacy_hbmcmc_output

        output_metadata["postprocessing_input_contract"] = "modern_inversion_output"
        with timed("rhime.output.legacy_postprocess"):
            legacy_out = make_legacy_hbmcmc_output(
                inv_out,
                country_file=country_file,
                use_bc=model_spec.use_bc,
            )
        outputs["legacy"] = legacy_out

        if output_spec.output_path is not None:
            Path(output_spec.output_path).mkdir(parents=True, exist_ok=True)
            legacy_file = _define_derived_output_filename(
                output_spec,
                species=model_spec.species,
                domain=model_spec.domain,
                output_name=output_spec.output_name,
                start_date=run_spec.start_date,
                ext=".nc",
            )
            with timed("rhime.output.legacy_netcdf_write", path=legacy_file):
                legacy_out.to_netcdf(legacy_file, mode="w", encoding=ncdf_encoding(legacy_out))
            output_metadata["legacy_output_path"] = str(legacy_file)

    return RhimeOutputBundle(inv_out=inv_out, outputs=outputs, output_metadata=output_metadata)


def _make_multisector_flux_diagnostics(
    inv_out: InversionOutput,
) -> xr.Dataset:
    """Create sector-aware flux diagnostics with the shared postprocessing layer."""
    from openghg_inversions.postprocessing.make_outputs import make_sector_flux_outputs

    return make_sector_flux_outputs(
        inv_out,
        stats=["mean"],
        include_scale_factors=True,
        report_flux_on_inversion_grid=False,
    )


def make_multisector_output_bundle(
    *,
    output_spec: RhimeOutputSpec,
    run_spec: RhimeRunSpec,
    model_spec: RhimeModelSpec,
    idata: az.InferenceData,
    prepared: RhimePreparedInputs,
    country_file: str | None,
) -> RhimeOutputBundle:
    """Create and optionally save transitional multi-sector RHIME outputs."""
    with timed("rhime.output.inversion_output_create", output_format=output_spec.output_format):
        inv_out_for_outputs = _make_inversion_output(
            prepared=prepared,
            idata=idata,
            run_spec=run_spec,
            model_spec=model_spec,
            output_spec=output_spec,
        )
    inv_out = None
    with timed("rhime.output.multisector_diagnostics"):
        diagnostics = _make_multisector_flux_diagnostics(inv_out_for_outputs)
    outputs: dict[str, Any] = {"sector_flux_diagnostics": diagnostics}
    output_metadata: dict[str, Any] = {}
    if output_spec.output_format != "none":
        inv_out = inv_out_for_outputs
        outputs["inversion_output"] = inv_out
        output_metadata["inversion_output_contract"] = "modern"

        inv_out_path = _resolve_output_path(
            output_spec.save_inversion_output,
            output_spec.output_path,
            f"{output_spec.output_name}{run_spec.start_date}_inversion_output.nc",
        )
        if inv_out_path is not None:
            inv_out_path.parent.mkdir(parents=True, exist_ok=True)
            with timed("rhime.output.inversion_output_save", path=inv_out_path):
                inv_out.save(inv_out_path)
            output_metadata["inversion_output_path"] = str(inv_out_path)

    if output_spec.output_format == "paris":
        paris_kwargs = dict(output_spec.paris_postprocessing_kwargs or {})
        template_version = paris_kwargs.pop("template_version", None)
        if template_version == "latest":
            from openghg_inversions.postprocessing.make_paris_outputs import (
                infer_flux_frequency,
                paris_flux_output,
            )

            flux_frequency = paris_kwargs.pop("flux_frequency", None)
            if flux_frequency is None:
                flux_frequency = infer_flux_frequency(inv_out_for_outputs.flux)
            time_point = paris_kwargs.pop("time_point", "midpoint")
            report_mode = paris_kwargs.pop("report_mode", False)
            inversion_grid = paris_kwargs.pop("inversion_grid", True)
            country_selection_kwargs = {}
            if "country_selections" in paris_kwargs:
                country_selection_kwargs["country_selections"] = paris_kwargs.pop("country_selections")
            if paris_kwargs:
                unexpected = ", ".join(sorted(paris_kwargs))
                raise ValueError(
                    f"Unsupported multi-sector latest PARIS postprocessing kwargs: {unexpected}."
                )

            output_metadata["paris_note"] = (
                "Multi-sector PARIS latest flux total output was generated; "
                "multi-sector PARIS concentration output is not implemented yet."
            )
            flux_outs = paris_flux_output(
                inv_out_for_outputs,
                country_file=country_file,
                time_point=time_point,
                report_mode=report_mode,
                inversion_grid=inversion_grid,
                flux_frequency=flux_frequency,
                template_version="latest",
                **country_selection_kwargs,
            )
            outputs["paris_flux"] = flux_outs

            if output_spec.output_path is not None:
                Path(output_spec.output_path).mkdir(parents=True, exist_ok=True)
                flux_file = _define_output_filename(
                    output_spec.output_path,
                    model_spec.species,
                    model_spec.domain,
                    output_spec.output_name + "_flux",
                    run_spec.start_date,
                    ext=".nc",
                )
                write_netcdf_preserving_bounds_attrs(flux_outs, flux_file, unlimited_dims=["time"])
                output_metadata["paris_flux_path"] = str(flux_file)
        else:
            output_metadata["paris_note"] = (
                "Multi-sector PARIS output requires paris_postprocessing_kwargs "
                "with template_version='latest'; sector-aware diagnostics were generated instead."
            )
    if output_spec.output_path is not None and output_spec.output_format != "none":
        Path(output_spec.output_path).mkdir(parents=True, exist_ok=True)
        diagnostics_path = (
            Path(output_spec.output_path)
            / f"{output_spec.output_name}{run_spec.start_date}_sector_flux_diagnostics.nc"
        )
        with timed("rhime.output.multisector_diagnostics_netcdf_write", path=diagnostics_path):
            diagnostics.to_netcdf(diagnostics_path, mode="w", encoding=ncdf_encoding(diagnostics))
        output_metadata["sector_flux_diagnostics_path"] = str(diagnostics_path)

    return RhimeOutputBundle(inv_out=inv_out, outputs=outputs, output_metadata=output_metadata)
