"""RHIME output construction and persistence helpers."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, cast

import arviz as az
import xarray as xr

from openghg_inversions.array_ops import sparse_xr_dot
from openghg_inversions.inversion_data import RhimePreparedInputs
from openghg_inversions.models import RhimeModelSpec
from openghg_inversions.postprocessing.inversion_output import (
    InversionOutput,
    _reset_serialisation_multiindexes,
)
from openghg_inversions.rhime.sampling import RhimeSampler
from openghg_inversions.rhime.specs import OutputFilenameConvention, RhimeOutputSpec, RhimeRunSpec
from openghg_inversions.utils import ncdf_encoding


@dataclass(frozen=True)
class RhimeOutputBundle:
    """Outputs and metadata generated by RHIME output helpers."""

    inv_out: InversionOutput | None = None
    outputs: dict[str, Any] = field(default_factory=dict)
    output_metadata: dict[str, Any] = field(default_factory=dict)


def _resolve_output_path(
    save_setting: str | Path | bool, output_path: str | None, filename: str
) -> Path | None:
    """Resolve an optional output path from a bool/path save setting."""
    if not save_setting:
        return None
    if isinstance(save_setting, str | Path):
        return Path(save_setting)
    if output_path is None:
        raise ValueError("An output path is required when saving RHIME artifacts.")
    return Path(output_path) / filename


def _define_output_filename(
    output_path: str | Path,
    species: str,
    domain: str,
    output_name: str,
    start_date: str,
    *,
    filename_convention: OutputFilenameConvention = "rhime",
    ext: str = ".nc",
) -> Path:
    """Create a derived NetCDF filename using the selected convention."""
    if filename_convention == "legacy":
        filename = f"{species.upper()}_{domain}_{output_name}_{start_date}{ext}"
    else:
        filename = f"{output_name}_{species}_{domain}_{start_date}{ext}"
    return Path(output_path) / filename


def _define_derived_output_filename(
    output_spec: RhimeOutputSpec,
    *,
    species: str,
    domain: str,
    output_name: str,
    start_date: str,
    ext: str = ".nc",
) -> Path:
    """Create a derived-output filename using the requested convention."""
    if output_spec.output_path is None:
        raise ValueError("An output path is required when saving RHIME outputs.")
    return _define_output_filename(
        output_spec.output_path,
        species,
        domain,
        output_name,
        start_date,
        filename_convention=output_spec.output_filename_convention,
        ext=ext,
    )


def _save_inferencedata(idata: az.InferenceData, path: str | Path) -> None:
    """Save InferenceData, preferring the h5netcdf backend with fallbacks."""
    if isinstance(idata, az.InferenceData):
        idata = cast(Any, az.InferenceData)(
            **{group: _reset_serialisation_multiindexes(idata[group]) for group in idata.groups()}
        )

    failures = []
    for engine in ("h5netcdf", None, "netcdf4"):
        try:
            if engine is None:
                idata.to_netcdf(str(path), compress=True)
            else:
                idata.to_netcdf(str(path), engine=engine, compress=True)
        except Exception as exc:
            engine_name = "arviz-default" if engine is None else engine
            failures.append(f"{engine_name}: {exc}")
        else:
            return

    joined_failures = "\n".join(failures)
    raise RuntimeError(
        f"Could not save RHIME trace to {path}. Tried h5netcdf, ArviZ default, and netcdf4:\n{joined_failures}"
    )


def _materialise_basis_and_flux_for_output(
    prepared: RhimePreparedInputs,
) -> tuple[xr.DataArray, xr.DataArray]:
    """Return materialised arrays for transitional output adapters.

    TODO(#383/#429): postprocessing should consume ``BasisFunctions`` directly
    rather than requiring the runner to materialise a flat basis and flux.
    """
    basis = prepared.basis_functions.operator.basis_matrix
    current_state_dim = prepared.basis_functions.operator.meta.state_dim
    if current_state_dim != "region":
        basis = basis.rename({current_state_dim: "region"})
    region_coord = prepared.inv_inputs.region
    if region_coord.name is None:
        raise ValueError("prepared.inv_inputs.region must be named so it can be used for reindexing.")
    basis = basis.reindex({region_coord.name: region_coord})
    return basis, prepared.basis_functions.flux


def _make_inversion_output(
    *,
    prepared: RhimePreparedInputs,
    idata: az.InferenceData,
    run_spec: RhimeRunSpec,
    model_spec: RhimeModelSpec,
    output_spec: RhimeOutputSpec,
    sampler: RhimeSampler | None = None,
) -> InversionOutput:
    """Create the modern RHIME InversionOutput without fixedbasis legacy adapters."""
    return InversionOutput(
        inv_inputs=prepared.inv_inputs,
        basis_functions=prepared.basis_functions,
        trace=idata,
        run_metadata={
            "start_date": run_spec.start_date,
            "end_date": run_spec.end_date,
            "sites": list(run_spec.sites),
            "averaging_period": list(run_spec.averaging_period),
            "split_by_sectors": run_spec.split_by_sectors,
            "basis_artifact_source": prepared.basis_artifact_source,
            "site_lats": list(prepared.site_lats) if prepared.site_lats is not None else None,
            "site_lons": list(prepared.site_lons) if prepared.site_lons is not None else None,
        },
        model_metadata=asdict(model_spec),
        output_metadata={
            "output_format": output_spec.output_format,
            "output_path": output_spec.output_path,
            "output_name": output_spec.output_name,
            "save_trace": output_spec.save_trace,
            "save_inversion_output": output_spec.save_inversion_output,
            "sampler": _sampler_metadata(sampler),
        },
        provenance={
            "contract": "modern_rhime_inversion_output",
            "compatibility_issue": "401",
        },
    )


def _sampler_metadata(sampler: RhimeSampler | None) -> dict[str, int | str] | None:
    """Return serialisable sampler metadata for compatibility output attrs."""
    if sampler is None:
        return None
    return {
        "draws": sampler.draws,
        "burn": sampler.burn,
        "tune": sampler.tune,
        "chains": sampler.chains,
        "nuts_sampler": sampler.nuts_sampler,
    }


def make_standard_output_bundle(
    *,
    output_spec: RhimeOutputSpec,
    run_spec: RhimeRunSpec,
    model_spec: RhimeModelSpec,
    idata: az.InferenceData,
    prepared: RhimePreparedInputs,
    country_file: str | None,
    sampler: RhimeSampler | None = None,
) -> RhimeOutputBundle:
    """Create and optionally save standard RHIME outputs."""
    if output_spec.output_format == "none":
        return RhimeOutputBundle()

    outputs: dict[str, Any] = {}
    output_metadata: dict[str, Any] = {}
    inv_out = _make_inversion_output(
        prepared=prepared,
        idata=idata,
        run_spec=run_spec,
        model_spec=model_spec,
        output_spec=output_spec,
        sampler=sampler,
    )
    outputs["inversion_output"] = inv_out
    output_metadata["inversion_output_contract"] = "modern"

    trace_path = _resolve_output_path(
        output_spec.save_trace,
        output_spec.output_path,
        f"{output_spec.output_name}{run_spec.start_date}_trace.nc",
    )
    if trace_path is not None:
        trace_path.parent.mkdir(parents=True, exist_ok=True)
        _save_inferencedata(idata, trace_path)
        output_metadata["trace_path"] = str(trace_path)

    inv_out_path = _resolve_output_path(
        output_spec.save_inversion_output,
        output_spec.output_path,
        f"{output_spec.output_name}{run_spec.start_date}_inversion_output.nc",
    )
    if inv_out_path is not None:
        inv_out_path.parent.mkdir(parents=True, exist_ok=True)
        inv_out.save(inv_out_path)
        output_metadata["inversion_output_path"] = str(inv_out_path)

    if output_spec.output_format == "basic":
        from openghg_inversions.postprocessing.make_outputs import basic_output

        output_metadata["postprocessing_input_contract"] = "modern_inversion_output"
        outputs["basic"] = basic_output(inv_out, country_file=country_file)
    elif output_spec.output_format == "paris":
        from openghg_inversions.postprocessing.make_paris_outputs import make_paris_outputs

        output_metadata["postprocessing_input_contract"] = "modern_inversion_output"
        obs_avg_period = prepared.averaging_period[0] or "0h"
        kwargs = output_spec.paris_postprocessing_kwargs or {}
        flux_outs, conc_outs = make_paris_outputs(
            inv_out,
            country_file=country_file,
            domain=model_spec.domain,
            obs_avg_period=obs_avg_period,
            **kwargs,
        )
        outputs["paris_flux"] = flux_outs
        outputs["paris_concentration"] = conc_outs

        if output_spec.output_path is not None:
            Path(output_spec.output_path).mkdir(parents=True, exist_ok=True)
            conc_file = _define_derived_output_filename(
                output_spec,
                species=model_spec.species,
                domain=model_spec.domain,
                output_name=output_spec.output_name + "_conc",
                start_date=run_spec.start_date,
                ext=".nc",
            )
            flux_file = _define_derived_output_filename(
                output_spec,
                species=model_spec.species,
                domain=model_spec.domain,
                output_name=output_spec.output_name + "_flux",
                start_date=run_spec.start_date,
                ext=".nc",
            )
            conc_outs.to_netcdf(
                conc_file, unlimited_dims=["time"], mode="w", encoding=ncdf_encoding(conc_outs)
            )
            flux_outs.to_netcdf(
                flux_file, unlimited_dims=["time"], mode="w", encoding=ncdf_encoding(flux_outs)
            )
            output_metadata["paris_concentration_path"] = str(conc_file)
            output_metadata["paris_flux_path"] = str(flux_file)
    elif output_spec.output_format == "legacy":
        from openghg_inversions.postprocessing.legacy_outputs import make_legacy_hbmcmc_output

        output_metadata["postprocessing_input_contract"] = "modern_inversion_output"
        legacy_out = make_legacy_hbmcmc_output(
            inv_out,
            country_file=country_file,
            use_bc=model_spec.use_bc,
        )
        outputs["legacy"] = legacy_out

        if output_spec.output_path is not None:
            Path(output_spec.output_path).mkdir(parents=True, exist_ok=True)
            legacy_file = _define_derived_output_filename(
                output_spec,
                species=model_spec.species,
                domain=model_spec.domain,
                output_name=output_spec.output_name,
                start_date=run_spec.start_date,
                ext=".nc",
            )
            legacy_out.to_netcdf(legacy_file, mode="w", encoding=ncdf_encoding(legacy_out))
            output_metadata["legacy_output_path"] = str(legacy_file)

    return RhimeOutputBundle(inv_out=inv_out, outputs=outputs, output_metadata=output_metadata)


def _make_multisector_flux_diagnostics(
    *,
    idata: az.InferenceData,
    prepared: RhimePreparedInputs,
    model_spec: RhimeModelSpec,
) -> xr.Dataset:
    """Create provisional sector-aware posterior flux diagnostics.

    TODO(#398/#429): replace this runner-local special case with
    sector-aware postprocessing once the modern output layer supports multiple
    sectors and ``BasisFunctions`` reconstruction directly.

    Args:
        idata: InferenceData returned by RHIME sampling.
        prepared: Prepared RHIME input object containing retained basis functions.
        model_spec: Model spec containing sector names and variable suffixes.

    Returns:
        Dataset containing posterior mean scaling factors, sector posterior flux
        means, and total posterior flux mean.
    """
    basis, flux = _materialise_basis_and_flux_for_output(prepared)
    posterior_flux = []
    posterior_scaling = []

    for sector in model_spec.sectors:
        x_name = f"x_{sector.variable_suffix}"
        x_mean = cast(Any, idata).posterior[x_name].mean(("chain", "draw"))
        scale_grid = sparse_xr_dot(basis, x_mean)
        sector_flux = flux.sel(source=sector.flux_source) if "source" in flux.dims else flux
        posterior_scaling.append(scale_grid.expand_dims(sector=[sector.name]))
        posterior_flux.append((scale_grid * sector_flux).expand_dims(sector=[sector.name]))

    scaling = xr.concat(posterior_scaling, dim="sector").rename("posterior_scaling_mean")
    flux_by_sector = xr.concat(posterior_flux, dim="sector").rename("posterior_flux_mean")
    total_flux = flux_by_sector.sum("sector").rename("posterior_flux_total_mean")
    return xr.merge([scaling, flux_by_sector, total_flux])


def make_multisector_output_bundle(
    *,
    output_spec: RhimeOutputSpec,
    run_spec: RhimeRunSpec,
    model_spec: RhimeModelSpec,
    idata: az.InferenceData,
    prepared: RhimePreparedInputs,
) -> RhimeOutputBundle:
    """Create and optionally save transitional multi-sector RHIME outputs."""
    inv_out = None
    diagnostics = _make_multisector_flux_diagnostics(
        idata=idata,
        prepared=prepared,
        model_spec=model_spec,
    )
    outputs: dict[str, Any] = {"sector_flux_diagnostics": diagnostics}
    output_metadata: dict[str, Any] = {}
    if output_spec.output_format != "none":
        inv_out = _make_inversion_output(
            prepared=prepared,
            idata=idata,
            run_spec=run_spec,
            model_spec=model_spec,
            output_spec=output_spec,
        )
        outputs["inversion_output"] = inv_out
        output_metadata["inversion_output_contract"] = "modern"

        inv_out_path = _resolve_output_path(
            output_spec.save_inversion_output,
            output_spec.output_path,
            f"{output_spec.output_name}{run_spec.start_date}_inversion_output.nc",
        )
        if inv_out_path is not None:
            inv_out_path.parent.mkdir(parents=True, exist_ok=True)
            inv_out.save(inv_out_path)
            output_metadata["inversion_output_path"] = str(inv_out_path)

    if output_spec.output_format == "paris":
        output_metadata["paris_note"] = (
            "Multi-sector PARIS schema support is not implemented in issue #398; "
            "sector-aware modern diagnostics were generated instead."
        )
    if output_spec.output_path is not None and output_spec.output_format != "none":
        Path(output_spec.output_path).mkdir(parents=True, exist_ok=True)
        diagnostics_path = (
            Path(output_spec.output_path)
            / f"{output_spec.output_name}{run_spec.start_date}_sector_flux_diagnostics.nc"
        )
        diagnostics.to_netcdf(diagnostics_path, mode="w", encoding=ncdf_encoding(diagnostics))
        output_metadata["sector_flux_diagnostics_path"] = str(diagnostics_path)

    return RhimeOutputBundle(inv_out=inv_out, outputs=outputs, output_metadata=output_metadata)
