"""Compatibility imports; implementation lives in :mod:`openghg_inversions.recipes.stages`."""

from openghg_inversions.recipes.stages import (
    CHECK_SCHEMA_VERSION as CHECK_SCHEMA_VERSION,
    CONVERGENCE_CHECK_NAME as CONVERGENCE_CHECK_NAME,
    ModelKind as ModelKind,
    PREPARATION_CHECK_NAME as PREPARATION_CHECK_NAME,
    _PREPARATION_IDENTITY_EXCLUDED_OPTIONS as _PREPARATION_IDENTITY_EXCLUDED_OPTIONS,
    _STAGE_PATH_OPTIONS as _STAGE_PATH_OPTIONS,
    _build_prepared_model as _build_prepared_model,
    _check_result as _check_result,
    _check_stage as _check_stage,
    _filename_component as _filename_component,
    _load_output_binding as _load_output_binding,
    _load_prepared as _load_prepared,
    _load_stage_manifest as _load_stage_manifest,
    _output_path as _output_path,
    _resolve_stage_paths as _resolve_stage_paths,
    _sampler_from_sample_manifest as _sampler_from_sample_manifest,
    _stage_output_directory as _stage_output_directory,
    _validate_diagnostic_thresholds as _validate_diagnostic_thresholds,
    _verify_manifest_artifact as _verify_manifest_artifact,
    _verify_sample_manifest as _verify_sample_manifest,
    configuration_identity as configuration_identity,
    diagnose_rhime_stage as diagnose_rhime_stage,
    effective_configuration as effective_configuration,
    load_stage_params as load_stage_params,
    postprocess_rhime_stage as postprocess_rhime_stage,
    prepare_rhime_stage as prepare_rhime_stage,
    prior_predictive_stage as prior_predictive_stage,
    resolve_stage_setup as resolve_stage_setup,
    sample_rhime_stage as sample_rhime_stage,
)
