name: multi_gas_model_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pymc3
  - pymc
  - matplotlib-base
  - netcdf4
  - numpy
  - regionmask
  - xarray
  - iso3166
  - pandas
  - numexpr
  - tqdm
  - xesmf
  - yaml
  - iris
  - h5py
  - numba
  - scipy
  - pytest
  - pyfakefs
  - cachetools

  - python-dateutil
  - esmpy
  - ipympl
  - numexpr
  - natsort
  - imageio
