"""Compatibility aliases for reusable model components.

The canonical package configures PyTensor before importing backend components.
"""

from openghg_inversions.model_components import (
    configure_pytensor as configure_pytensor,
    CoordRegistry as CoordRegistry,
    CorrelatedLognormalPrior as CorrelatedLognormalPrior,
    CorrelatedStateResult as CorrelatedStateResult,
    LinearComponentResult as LinearComponentResult,
    AggregationErrorMode as AggregationErrorMode,
    FixedOuCachedSigmaTarget as FixedOuCachedSigmaTarget,
    MarginalQuadraticCache as MarginalQuadraticCache,
    ResolvedStateActivity as ResolvedStateActivity,
    PreparedLinearSensitivity as PreparedLinearSensitivity,
    StateActivity as StateActivity,
    ScalarSigmaEigenbasis as ScalarSigmaEigenbasis,
    add_scalar_sigma_eigen_likelihood as add_scalar_sigma_eigen_likelihood,
    add_coords as add_coords,
    attach_coord_registry as attach_coord_registry,
    get_coord_registry as get_coord_registry,
    registered_model as registered_model,
    restore_inferencedata_coords as restore_inferencedata_coords,
    parse_prior as parse_prior,
    prepare_scalar_sigma_eigenbasis as prepare_scalar_sigma_eigenbasis,
    save_scalar_sigma_eigenbasis as save_scalar_sigma_eigenbasis,
    load_scalar_sigma_eigenbasis as load_scalar_sigma_eigenbasis,
    add_model_data as add_model_data,
    add_correlated_lognormal_state as add_correlated_lognormal_state,
    add_correlated_lognormal_state_with_activity as add_correlated_lognormal_state_with_activity,
    add_coherent_affine_component as add_coherent_affine_component,
    add_linked_linear_component as add_linked_linear_component,
    add_linear_component as add_linear_component,
    apply_linear_sensitivity as apply_linear_sensitivity,
    add_sigma_component as add_sigma_component,
    add_site_sigma_gaussian_likelihood as add_site_sigma_gaussian_likelihood,
    add_offset_component as add_offset_component,
    active_prior_args as active_prior_args,
    detect_zero_sensitivity as detect_zero_sensitivity,
    prepare_linear_sensitivity as prepare_linear_sensitivity,
    resolve_state_activity as resolve_state_activity,
    __all__ as __all__,
)
