"""Experimental NumPy/Numba engines for spatial reversible-jump MCMC.

The package separates fixed-capacity Voronoi problems and states, explicit
Metropolis-Hastings proposal accounting, deterministic seeded sampling, and
adaptation of filtered RHIME fine-grid inputs. Alongside the independent-error
target, it now provides opt-in independent-site OU model-data mismatch with an
observation-error nugget and an opt-in shared hierarchy over the arithmetic
mean and standard deviation of the dynamic-coefficient prior. These additions
remain experimental and require an explicit extended schedule. Inferred
boundary conditions, multi-sector models, and parallel tempering remain
outside this slice.

A separate NumPy reference implementation samples active frontiers of one
canonical fixed-direction dyadic tree under a Gamma--Beta mass prior. It now
includes an explicit RHIME adapter, full-posterior compound schedule, and
separate durable checkpoint/output schema for real-data experiments. It
remains a restricted split/merge mixing baseline rather than a production
full-tiling model and deliberately does not widen the Voronoi state schema.
"""

from openghg_inversions.experimental.rjmcmc.core import (
    FixedDesignBlock,
    InferredOUErrorModel,
    TransDimensionalProblem,
    TransDimensionalState,
    aggregate_design_numba,
    aggregate_design_numpy,
    assign_cells_numba,
    assign_cells_numpy,
    build_state,
    gaussian_log_likelihood_numba,
    gaussian_log_likelihood_numpy,
    lognormal_coefficient_log_prior_numba,
    lognormal_coefficient_log_prior_numpy,
    uniform_log_k_prior,
    uniform_nucleus_set_log_prior,
)
from openghg_inversions.experimental.rjmcmc.checkpoint_io import (
    CHECKPOINT_SCHEMA_ID,
    CHECKPOINT_SCHEMA_VERSION,
    load_checkpoint,
    problem_fingerprint,
    save_checkpoint,
)
from openghg_inversions.experimental.rjmcmc.hierarchy import (
    SharedLognormalHierarchy,
    arithmetic_moments_to_log_state,
    arithmetic_moments_to_lognormal_parameters,
    log_moments_to_lognormal_parameters,
    shared_coefficient_log_prior_numba,
    shared_coefficient_log_prior_numpy,
    shared_hyperprior_log_density_numba,
    shared_hyperprior_log_density_numpy,
)
from openghg_inversions.experimental.rjmcmc.dyadic_tree import (
    CanonicalDyadicTree,
    DyadicFrontier,
    DyadicNode,
    NodeId,
    enumerate_frontiers,
    partition_counts_by_k,
)
from openghg_inversions.experimental.rjmcmc.gamma_beta_adapter import (
    GammaBetaRHIMEAdapterResult,
    gamma_beta_problem_from_rhime_inputs,
    initialize_gamma_beta_state,
)
from openghg_inversions.experimental.rjmcmc.gamma_beta_compound_sampling import (
    GAMMA_BETA_COMPOUND_SCHEDULE_ID,
    CompoundSlot,
    GammaBetaCompoundCheckpoint,
    GammaBetaCompoundConfig,
    GammaBetaCompoundKernelSettings,
    GammaBetaCompoundSamplingResult,
    GammaBetaCompoundTrace,
    continue_gamma_beta_compound,
    sample_gamma_beta_compound,
)
from openghg_inversions.experimental.rjmcmc.gamma_beta_io import (
    GAMMA_BETA_CHECKPOINT_SCHEMA_ID,
    GAMMA_BETA_CHECKPOINT_SCHEMA_VERSION,
    GAMMA_BETA_MANIFEST_SCHEMA_ID,
    GAMMA_BETA_MANIFEST_SCHEMA_VERSION,
    GAMMA_BETA_TRACE_SCHEMA_ID,
    GAMMA_BETA_TRACE_SCHEMA_VERSION,
    RunManifest,
    build_gamma_beta_run_manifest,
    canonical_gamma_beta_run_manifest,
    gamma_beta_compound_trace_to_dataset,
    gamma_beta_problem_fingerprint,
    gamma_beta_state_fingerprint,
    load_gamma_beta_checkpoint,
    save_gamma_beta_checkpoint,
)
from openghg_inversions.experimental.rjmcmc.gamma_beta_proposals import (
    GammaBetaMove,
    GammaBetaTransitionTerms,
    accept_or_reject as accept_gamma_beta_or_reject,
    propose_fraction_refresh,
    propose_fixed_coefficient as propose_gamma_beta_fixed_coefficient,
    propose_merge,
    propose_root_refresh,
    propose_split,
)
from openghg_inversions.experimental.rjmcmc.gamma_beta_sampling import (
    GAMMA_BETA_STRUCTURAL_SCHEDULE_ID,
    GammaBetaCheckpoint,
    GammaBetaSamplerConfig,
    GammaBetaSamplingResult,
    GammaBetaTrace,
    continue_gamma_beta_tree,
    sample_gamma_beta_tree,
)
from openghg_inversions.experimental.rjmcmc.gamma_beta_tree import (
    GammaBetaTreePrior,
    GammaBetaTreeProblem,
    GammaBetaTreeState,
    TreePartitionPrior,
    build_gamma_beta_tree_state,
    render_cell_mass,
)
from openghg_inversions.experimental.rjmcmc.likelihood import (
    IndependentSiteOUData,
    ou_log_likelihood_numba,
    ou_log_likelihood_numpy,
)
from openghg_inversions.experimental.rjmcmc.mixing_diagnostics import (
    STRUCTURAL_MOVES,
    DerivedStructuralDiagnostics,
    NucleusResidenceIntervals,
    RegionLineageIntervals,
    StructuralDiagnostics,
    StructuralDiagnosticsProvenance,
    concatenate_structural_diagnostics,
    derive_nucleus_residence_intervals,
    derive_region_lineage_intervals,
    derive_structural_diagnostics,
)
from openghg_inversions.experimental.rjmcmc.proposals import (
    TransitionTerms,
    accept_or_reject,
    propose_birth,
    propose_coefficient,
    propose_correlation_timescale,
    propose_death,
    propose_fixed_coefficient,
    propose_global_move,
    propose_local_move,
    propose_mismatch_sd,
    propose_shared_hierarchy,
)
from openghg_inversions.experimental.rjmcmc.postprocessing import (
    DEFAULT_QUANTILES,
    FineGridPosteriorSummary,
    PosteriorPredictionSummary,
    posterior_mean_prediction,
    reconstruct_fine_grid_samples,
    summarize_fine_grid_posterior,
    summarize_posterior_prediction,
)
from openghg_inversions.experimental.rjmcmc.rhime_adapter import problem_from_rhime_inputs
from openghg_inversions.experimental.rjmcmc.retention import RetentionSettings
from openghg_inversions.experimental.rjmcmc.sampling import (
    FIXED_BLOCK_SCHEDULE_ID,
    LUNT_OPPORTUNITY_MATCHED_FIXED_BLOCK_SCHEDULE_ID,
    LUNT_OPPORTUNITY_MATCHED_OU_HIERARCHY_SCHEDULE_ID,
    LUNT_OPPORTUNITY_MATCHED_OU_HIERARCHY_SCHEDULE_PROFILE,
    LUNT_OPPORTUNITY_MATCHED_OU_SCHEDULE_ID,
    LUNT_OPPORTUNITY_MATCHED_OU_SCHEDULE_PROFILE,
    LUNT_OPPORTUNITY_MATCHED_SCHEDULE_PROFILE,
    SCHEDULE_ID,
    KernelSettings,
    PCG64State,
    SamplerCheckpoint,
    SamplerConfig,
    SamplingResult,
    SamplingTrace,
    ScheduleProfile,
    continue_sample,
    sample,
)
from openghg_inversions.experimental.rjmcmc.xarray_output import (
    sampling_trace_to_dataset,
    structural_diagnostics_from_dataset,
    structural_diagnostics_to_dataset,
)

__all__ = [
    "CHECKPOINT_SCHEMA_ID",
    "CHECKPOINT_SCHEMA_VERSION",
    "CanonicalDyadicTree",
    "CompoundSlot",
    "DEFAULT_QUANTILES",
    "DerivedStructuralDiagnostics",
    "DyadicFrontier",
    "DyadicNode",
    "FIXED_BLOCK_SCHEDULE_ID",
    "FineGridPosteriorSummary",
    "FixedDesignBlock",
    "GAMMA_BETA_CHECKPOINT_SCHEMA_ID",
    "GAMMA_BETA_CHECKPOINT_SCHEMA_VERSION",
    "GAMMA_BETA_COMPOUND_SCHEDULE_ID",
    "GAMMA_BETA_MANIFEST_SCHEMA_ID",
    "GAMMA_BETA_MANIFEST_SCHEMA_VERSION",
    "GAMMA_BETA_STRUCTURAL_SCHEDULE_ID",
    "GAMMA_BETA_TRACE_SCHEMA_ID",
    "GAMMA_BETA_TRACE_SCHEMA_VERSION",
    "GammaBetaCheckpoint",
    "GammaBetaCompoundCheckpoint",
    "GammaBetaCompoundConfig",
    "GammaBetaCompoundKernelSettings",
    "GammaBetaCompoundSamplingResult",
    "GammaBetaCompoundTrace",
    "GammaBetaMove",
    "GammaBetaRHIMEAdapterResult",
    "GammaBetaSamplerConfig",
    "GammaBetaSamplingResult",
    "GammaBetaTrace",
    "GammaBetaTransitionTerms",
    "GammaBetaTreePrior",
    "GammaBetaTreeProblem",
    "GammaBetaTreeState",
    "IndependentSiteOUData",
    "InferredOUErrorModel",
    "KernelSettings",
    "LUNT_OPPORTUNITY_MATCHED_FIXED_BLOCK_SCHEDULE_ID",
    "LUNT_OPPORTUNITY_MATCHED_OU_HIERARCHY_SCHEDULE_ID",
    "LUNT_OPPORTUNITY_MATCHED_OU_HIERARCHY_SCHEDULE_PROFILE",
    "LUNT_OPPORTUNITY_MATCHED_OU_SCHEDULE_ID",
    "LUNT_OPPORTUNITY_MATCHED_OU_SCHEDULE_PROFILE",
    "LUNT_OPPORTUNITY_MATCHED_SCHEDULE_PROFILE",
    "NucleusResidenceIntervals",
    "NodeId",
    "RegionLineageIntervals",
    "PCG64State",
    "PosteriorPredictionSummary",
    "RetentionSettings",
    "RunManifest",
    "SCHEDULE_ID",
    "STRUCTURAL_MOVES",
    "ScheduleProfile",
    "SamplerCheckpoint",
    "SamplerConfig",
    "SamplingResult",
    "SamplingTrace",
    "StructuralDiagnostics",
    "StructuralDiagnosticsProvenance",
    "SharedLognormalHierarchy",
    "TransDimensionalProblem",
    "TransDimensionalState",
    "TransitionTerms",
    "TreePartitionPrior",
    "accept_gamma_beta_or_reject",
    "accept_or_reject",
    "aggregate_design_numba",
    "aggregate_design_numpy",
    "arithmetic_moments_to_log_state",
    "arithmetic_moments_to_lognormal_parameters",
    "assign_cells_numba",
    "assign_cells_numpy",
    "build_state",
    "build_gamma_beta_tree_state",
    "build_gamma_beta_run_manifest",
    "canonical_gamma_beta_run_manifest",
    "concatenate_structural_diagnostics",
    "continue_gamma_beta_compound",
    "continue_sample",
    "continue_gamma_beta_tree",
    "derive_nucleus_residence_intervals",
    "derive_region_lineage_intervals",
    "derive_structural_diagnostics",
    "enumerate_frontiers",
    "gaussian_log_likelihood_numba",
    "gaussian_log_likelihood_numpy",
    "gamma_beta_compound_trace_to_dataset",
    "gamma_beta_problem_fingerprint",
    "gamma_beta_state_fingerprint",
    "gamma_beta_problem_from_rhime_inputs",
    "initialize_gamma_beta_state",
    "load_gamma_beta_checkpoint",
    "lognormal_coefficient_log_prior_numba",
    "lognormal_coefficient_log_prior_numpy",
    "log_moments_to_lognormal_parameters",
    "load_checkpoint",
    "problem_fingerprint",
    "propose_fraction_refresh",
    "propose_gamma_beta_fixed_coefficient",
    "propose_birth",
    "propose_coefficient",
    "propose_correlation_timescale",
    "propose_death",
    "propose_fixed_coefficient",
    "propose_global_move",
    "propose_local_move",
    "propose_merge",
    "propose_mismatch_sd",
    "propose_shared_hierarchy",
    "propose_root_refresh",
    "propose_split",
    "posterior_mean_prediction",
    "problem_from_rhime_inputs",
    "reconstruct_fine_grid_samples",
    "render_cell_mass",
    "ou_log_likelihood_numba",
    "ou_log_likelihood_numpy",
    "sample",
    "sample_gamma_beta_compound",
    "sample_gamma_beta_tree",
    "sampling_trace_to_dataset",
    "save_gamma_beta_checkpoint",
    "save_checkpoint",
    "shared_coefficient_log_prior_numba",
    "shared_coefficient_log_prior_numpy",
    "shared_hyperprior_log_density_numba",
    "shared_hyperprior_log_density_numpy",
    "structural_diagnostics_from_dataset",
    "structural_diagnostics_to_dataset",
    "summarize_fine_grid_posterior",
    "summarize_posterior_prediction",
    "partition_counts_by_k",
    "uniform_log_k_prior",
    "uniform_nucleus_set_log_prior",
]
