name: OpenGHG Inversions tests

on:
  push:
    branches: [main, devel]
    tags:
    - '*'
  pull_request:
    branches: [main, devel]
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  openghg-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # working-directory: .github/workflows
    outputs:
      latest_minor: ${{ steps.versions.outputs.OPENGHG_LATEST_MINOR }}
      previous_minor: ${{ steps.versions.outputs.OPENGHG_PREVIOUS_MINOR }}
      devel: ${{ steps.versions.outputs.OPENGHG_DEVEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set openghg latest and previous minor versions
        id: versions
        run: |
          echo "OPENGHG_LATEST_MINOR=openghg==$(bash .github/workflows/openghg_versions.sh)" >> "$GITHUB_OUTPUT"
          echo "OPENGHG_PREVIOUS_MINOR=openghg==$(bash .github/workflows/openghg_versions.sh -N 1)" >> "$GITHUB_OUTPUT"
          echo "OPENGHG_DEVEL=git+https://github.com/openghg/openghg.git@devel" >> "$GITHUB_OUTPUT"
      - name: check openghg minor versions
        run: |
          echo "OPENGHG_LATEST_MINOR=${{ steps.versions.outputs.OPENGHG_LATEST_MINOR }}"
          echo "OPENGHG_PREVIOUS_MINOR=${{ steps.versions.outputs.OPENGHG_PREVIOUS_MINOR }}"

  test:
    name: Run tests on (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: openghg-version
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
        openghg-version: ["${{ needs.openghg-version.outputs.latest_minor }}", "${{ needs.openghg-version.outputs.previous_minor }}", "${{ needs.openghg-version.outputs.devel }}"]
        # python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: check versions
        run: |
          echo "${{ needs.openghg-version.outputs.latest_minor }}"
          echo "${{ needs.openghg-version.outputs.previous_minor }}"
          echo "${{ needs.openghg-version.outputs.devel }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install package
        run: |
          pip install --upgrade pip setuptools wheel
          pip install ${{ matrix.openghg-version }}
          pip install -r requirements.txt
          pip install -e .
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest tests/
