name: OpenGHG Inversions tests

on:
  push:
    branches: [main, devel]
    tags:
    - '*'
  pull_request:
    branches: [main, devel]
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  test:
    name: Run tests on (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
        openghg-version: ["openghg==0.7.1", "openghg==0.8", "git+https://github.com/openghg/openghg.git@devel"]
        # python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install package
        run: |
          pip install --upgrade pip setuptools wheel
          pip install ${{ matrix.openghg-version }}
          pip install -r requirements.txt
          pip install -e .
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest tests/
